<?php
/**
 * @var \Magenest\Blog\Block\Blog\View $block
 * @var \Magento\Framework\Escaper $escaper
 */

$blog = $block->getBlogObject();
?>

<p><?=$escaper->escapeHtml($blog->getTitle())?></p>
<p><?=$escaper->escapeHtml($blog->getAuthorId())?></p>
<p><?=$escaper->escapeHtml($blog->getDescription())?></p>
<p><?=$escaper->escapeHtml($blog->getContent())?></p>
<p><?=$escaper->escapeHtml($blog->getUrlRewrite())?></p>
<p><?=$escaper->escapeHtml($blog->getStatus())?></p>
